title: 
logo: /assets/img/emf-stencil-logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  repository_url: https://github.com/antoniogarmendia/emfsplitter
  zip_url: https://github.com/antoniogarmendia/emfsplitter/zipball/master
  tar_url: https://github.com/antoniogarmendia/emfsplitter/tarball/master

